server:
  port: 9295


spring:
  application:
    name: HYSTRIX-DASHBOARD
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296
      

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"